### ISSUE TITLE
Issues and suggestions in FD2

### ISSUE THREAD

**Issue by nful2** [freedoom/freedoom#1043] opened 2023-07-31 12:56 UTC
**Issues:**
1. map09 - can get stuck behind crates

https://github.com/freedoom/freedoom/assets/100768714/c070ef18-bb56-4167-9023-fc589c331cc0

2. map09 - How to get megarmor secret? (I know this map has been done by @Catoptromancy)
3. map14 - There is invisible wall preventing to take this secret.

https://github.com/freedoom/freedoom/assets/100768714/0778975a-b96f-4964-922d-875eb288c004

4. map18 - Supercharge is mistakenly placed near exit? Can't access it
![i4](https://github.com/freedoom/freedoom/assets/100768714/e784901d-bf13-419c-bca7-a84906b8648d)
5. map26 - how to get bonus?

https://github.com/freedoom/freedoom/assets/100768714/a5be319b-b579-436c-b9b9-1c9124bf2163

**Suggestions:**
6. map07 - enemies cannot move beyond invisible barrier

https://github.com/freedoom/freedoom/assets/100768714/ef09a147-7708-4dfb-9f76-50bc635e157f

7. map09 - there is red line beside yellow line on the door on the other side with the many boxes.
![s2](https://github.com/freedoom/freedoom/assets/100768714/b114b2d0-afed-4bbd-ace7-4ab96d746840)
8. map10 - caco can get stuck

https://github.com/freedoom/freedoom/assets/100768714/dbe0daca-9500-4223-bf39-6c66bd587490

9. map11 - Blue door is opened by enemies on the other side and becomes easy to go to the other side, instead of using the lift, which is the intended way to do it.
![s4](https://github.com/freedoom/freedoom/assets/100768714/0f1d8a2c-82fe-4f5e-a318-fea2846ca512)

10. map13 - technospider unable to come forward

https://github.com/freedoom/freedoom/assets/100768714/ec27a478-f741-4511-b9a3-44a39b5f7286

11. map13 - revenants with supercharge get woken up before releasing them, which fails from surprising the player. They can also attack. Also, the fight with arch vile with many revenants seems too difficult with less rocket ammo.

https://github.com/freedoom/freedoom/assets/100768714/fd1088cc-b4b7-4a53-b0d4-ebe0d048f390

12. map15 - don't make these teleporters lower in easy difficulty, as nothing spawns. I was ready for something to spawn, but nothing happened. Located near supercharge at the start at the top.
![s7](https://github.com/freedoom/freedoom/assets/100768714/9d6b4313-f53e-4dd7-9522-30ebd2247ebe)
13. map15 - place clip in centre, not at a corner. Also the stimpack at the opposite room.(both contain imps)

https://github.com/freedoom/freedoom/assets/100768714/a590d584-878a-4c30-8bec-e1bc649866c8

14. map16 - Two secrets inside one
![s9](https://github.com/freedoom/freedoom/assets/100768714/f8fe509e-3d67-4324-a3f9-00acc43eebe7)

15. map16 - caco can go too far. Player has to wait for him to be in shootable range. Can't remember which difficulty was this played in.

https://github.com/freedoom/freedoom/assets/100768714/08c7c9db-4d86-48ed-a020-f47597fde6d2

16. map16 - In med difficulty, Pain lord seemed more difficult than the revenant in hard difficulty. Interchange them in the two difficulties. Located in the room with exit door
![s11](https://github.com/freedoom/freedoom/assets/100768714/165d680b-d849-4305-b621-c9c469fb06e4)
17. map16 - In hard difficulty, replace caco with revenant in outside area near exit teleporter
18. map17 - megaarmor secret seems too easy
19. map17 - place one more bonus on the other side (hand) of the sofa

https://github.com/freedoom/freedoom/assets/100768714/7e1f536b-cd29-426e-a408-8aa6c5343d8a

20. map18 - Supercharge secret seems too easy by climbing crates
21. map19 - How to get secret with armor and rockets without straferunning (sr50)? What if someone doesn't know how to do sr50?
![s17](https://github.com/freedoom/freedoom/assets/100768714/7e1f90b0-95a2-4761-94bd-3b55f77cbe59)
22. map25 - Switch at start of map can be pressed by punching. Make it a bit far away to be able to be shootable using pistol. It can also be shooted without pressing the switch at the left.

https://github.com/freedoom/freedoom/assets/100768714/6bda737f-2593-47b9-8e04-d175a033827d

23. map25 - After grabbing yellow key, sometimes trilobites get stuck in the two spaces where they spawn. Make the space wider for them to come out easily.

https://github.com/freedoom/freedoom/assets/100768714/b3eb9143-4231-4e26-a76b-d790b7e95b3f

24. map25 - Exit doesn't get marked in red boundary in gzdoom
25. map25 - In hard difficulty, revenant near ssg seems too easy because it can be stunned using minigun. Place a pain lord instead.
26. map25 - In my run on hard difficulty, when you pick up rocket launcher, both worms teleport one by one from only left side (taking the door as reference) instead of teleporting from both sides together. Unable to do it again in another run.
27. map25 - Near the ssg, you can see corpse of pain bringer is visible through the floor.

https://github.com/freedoom/freedoom/assets/100768714/8ce3e40e-ed99-4cb3-8ad5-0ee9973a97a0

28. map11 - In the area after the three switch door, the enemies inside the wall (which open after pressing switch at the end of the room) wake up before pressing the switch, which fails to surprise the player of an attack.

**Comment by Catoptromancy** [comment] 2023-07-31 16:21
map09 has teleport in rocky lava room near shadowsphere.

**Comment by nful2** [comment] 2023-07-31 16:56
@Catoptromancy can you mention the issue you faced in map11? You said it in #959

**Comment by mc776** [comment] 2023-07-31 17:16
Anything I have not mentioned here that's in the OP, I intend to look into and fix:

Not a bug:
Map09
Intentionally signifying you need both keys to leave
Map11
Intentional setpiece where backup starts arriving as the fight progresses. 
Map13
May or may not be intentional but best to leave it as is - letting it come forward makes it too easy to avoid on your way to the blue door.
Map15
Hard disagree, stuff tends to get left in corners and it looks fine to me.
Map16
This was actually discussed during Inuk's review for thin secret sectors. It was decided to leave this intentionally like that as it fit the weirdness of the rest of the map.
The trilobites beeline for the player anyway, it's fine.
Map18
Not a bug, just a really obscure secret
Map25
Intentional attempt to replicate a broken elevator. This all presupposed the absolute necessity of having to hit the fire button at that point; that may not necessarily be the case, so I can look into changing this to something simpler.
Map26
Not a bug, just a jumping puzzle (and I confirm you can do this only using the forward key, no SR50)

I disagree:
Map16
I disagree as the octaminator is more mobile and is harder to evade.
The octaminator at the very end seems thematically inappropriate given the trilobites in that area.
Map17
Just let the player have it, it's a frustrating enough map as it is.
The health bonus is supposed to be evocative of a beer someone's got while they're watching TV. I think it still works, even if the bonus is no longer a bottle (at least it's roughly beer-coloured).
Map18
I think this should be fixed, but in the opposite direction: add one more small crate to let the player get up there without jump. It's a fairly hard fight with the necromancer in the tight area and if you get past it the only difference is a mildly frustrating jump after you retrace your steps (and then you do it all over again when you realize you missed that one health bonus in the corner).

**Comment by mc776** [comment] 2023-07-31 17:17
I believe the map11 secret problem was addressed in #1038.

**Comment by mc776** [comment] 2023-07-31 21:27
The problem with the Map25 exit is that there's a big scary not-quite-boss monsters that's sitting right on top of it and the idea is to defeat it before you can proceed. If it had just kinda been in the room somewhere then forcibly squeezing past it to trigger the exit would be fine, but here it's clearly supposed to be *right on top of the exit* at all times so trying to create a bigger set of exit lines would make it feel diegetically nonsensical.

**Comment by mc776** [comment] 2023-08-01 05:53
Re: Map07 monster blocking line, they're all projectile or hitscan monsters in there and it's a good way to keep them from bunching up too much or wandering too far from where they're supposed to be engaging the player. I think it's best to leave it as it is.

**Comment by nful2** [comment] 2023-08-01 09:08
What about 5,8,11,21 and 27?

**Comment by nful2** [comment] 2023-08-01 09:40
Also, mark the supercharge near the exit of map18 as a secret?

**Comment by mc776** [comment] 2023-08-01 15:01
map10 trilobite - cannot replicate, probably unfixable without getting rid of all trilobites in that area

map13 octaminators - seems intended

map18 non-secret-flag - never even thought to check that lol. Who keeps adding these stupid light effects into secrets??

map19 armour - as a matter of principle i *strongly* disagree with the notion that we should make everything non-sr50-friendly, *but* this is definitely not super vanilla friendly when there are spectres blocking the way underneath. Maybe it's best to just get rid of that trench altogether?

map25 sprite clip - unfixable engine issue

**Comment by nful2** [comment] 2023-08-02 09:14
Found one more bug in map26 - switch for secret lift shows blue door instead of blue switch/object

https://github.com/freedoom/freedoom/assets/100768714/3f6848eb-4f9b-490d-a6b5-c0046acf8cd3

**Comment by mc776** [comment] 2023-08-02 14:50
1 damage floors don't exist, obligatory damage as a reward for finding something sounds bad, and i'm more inclined to think of invisible blocking monsters as more bug than feature.

**Comment by nful2** [comment] 2023-08-02 16:01
@mc776 suggestions/issues map29:
1. Switch for lowering teleporter inside the minigunner trap room seems too random to me. There is no hint like arrow or different coloured wall, etc.
2. In my easy run, after pressing the red switch and killing all minigunners, then got the skag. I went inside again (to check if I missed something) and all the 4 doors closed!

**Comment by mc776** [comment] 2023-08-02 16:50
1. It actually is a different coloured/textured wall - it takes a very close look but I think as far as hard level secrets go this one isn't too bad.

2. It looks like the intended effect is that you open that door the first time, go in and it closes behind you... except it's not the right door and it wouldn't be triggered in time anyway. Weird, but not sure if actually worth fixing given how weird and jank that little house is already.

**Comment by nful2** [comment] 2023-08-05 10:17
@mc776 one suggestion for map11 - remove red skeleton key as a secret area as the teleporter to reach it is already a secret

**Comment by mc776** [comment] 2023-08-05 16:44
Turned out there were multiple sectors with the secret tag inadvertently left in, oops

**Comment by nful2** [comment] 2023-08-08 10:04
@mc776 Can you tell @Xindage to check map11 and verify it in #959

**Comment by mc776** [comment] 2023-08-10 01:29
Is there anything still outstanding here or can this be closed?

**Closed** 2023-08-10 17:34 UTC
Labels: bug, levels
