### ISSUE TITLE
Aquatex textures affected by Tutti-Frutti effect.

### ISSUE THREAD

**Issue by jewellds** [freedoom/freedoom#323] opened 2016-10-19 06:32 UTC
Many of the new Aquatex textures are 64x64 (or smaller) and exibit the Tutti-Frutti effect in engines that have that bug (EG: Vanilla, Chocolate Doom). This could be fixed by expanding them to be 128 pixels tall.
![doom49](https://cloud.githubusercontent.com/assets/6622575/19507918/deb308b0-95cd-11e6-8a93-73600bfe268c.png)

Additionally, PIPE15 and PIPE16 are completely blank.
![doom60](https://cloud.githubusercontent.com/assets/6622575/19507922/e691d21e-95cd-11e6-9897-997205c235e4.png)

Test wad for Aquatex: [aquatestv5.zip](https://github.com/freedoom/freedoom/files/538100/aquatestv5.zip)

**Comment by Voros2** [comment] 2016-10-19 09:20
It seems I forgot to upload pipe15 and pipe16. That can be fixed.

As for the 64x64 textures, removing them from the IWADs would be a better idea. Or converting them into flats (if not already). 

You say this is only in vanilla/chocolate?

**Comment by jmickle66666666** [comment] 2016-10-19 09:56
The 64x64 textures are mostly just texture versions of the flats, iirc. It can be fixed by stacking 2 of them as patches in 128x64 textures. The original texture set was designed for boom, so there's bound to be a little work making sure they're all fine for vanilla.

**Comment by Voros2** [comment] 2016-10-19 10:33
Yes you do remember correctly. So I'll just remove them. Ok with you? It'll save space too.

**Comment by jmickle66666666** [comment] 2016-10-19 10:34
Well they are still handy as textures so I'm not sure removing them is necessary.

**Comment by Voros2** [comment] 2016-10-19 10:50
Well, I'd like to see this issue get fixed soon, and there's plenty of fabulous Aquatex textures inside, more than 200. Removing some non-vanilla-compatible textures, especially when they're just flats converted to textures, shouldn't be a big problem to mappers (because they've got over 200 more to choose from). 

Q: if the height is 64, but not the width eg 128, will it still have tutti frutti effects?

**Comment by jmickle66666666** [comment] 2016-10-19 10:53
The height must be 128 for it to avoid the tutti frutti effect. You can create a texture definition and stack two of the 64x64 patches to make it a 128x64 texture without having to waste any filesize. This will entirely fix the issue.

**Comment by Voros2** [comment] 2016-10-19 11:54
Oh yeah! That can fix patches easily. I'll get to work with that then.

**Comment by Voros2** [comment] 2016-10-19 14:29
Do the X offsets need to be changed also?

**Comment by jmickle66666666** [comment] 2016-10-19 14:30
Nope, just place two of the 64x patches on top of each other.

**Comment by Voros2** [comment] 2016-10-19 16:06
Im already 90% done. Just have to deal with AQLITE01-20something now. 
*sigh*
Thanks for informing me about the previous question, and giving a response I wanted to hear.

**Comment by Voros2** [comment] 2016-10-22 00:59
Thanks for notifying.

**Comment by fragglet** [comment] 2016-10-23 19:01
Fixed by #324.

**Closed by fragglet** 2016-10-23 19:01 UTC
