### ISSUE TITLE
Double-barrel shotgun becomes a DehackedPickup in GZDoom

### ISSUE THREAD

**Issue by Talon1024** [freedoom/freedoom#1151] opened 2023-10-17 00:09 UTC
I like to play Doom/Freedoom with GZDoom and the [Intelligent Supplies](https://forum.zdoom.org/viewtopic.php?t=71897) mod. However, when I play Freedoom: Phase 2 with the Intelligent Supplies mod, picking up the double-barrel shotgun is not "intelligent", even with intelligent weapon pickups enabled.

Pointing at a double-barrel shotgun pickup and running the `info` command tells me that double-barrel shotgun pickups become DehackedPickups, which is probably why picking up a double-barrel shotgun is not "intelligent".

This isn't a problem with the super shotguns in vanilla Doom 2, however.

**Comment by mc776** [comment] 2023-10-17 06:24
> Pickups created by Dehacked are also not supported due to not using base GZDoom class types. 

This was a problem that was solved decades ago. How did the modder manage to fuck this up!?

**Comment by mc776** [comment] 2023-10-17 06:25
Honestly at this point I think we should just abandon the idea of GZDoom compatibility...

**Comment by mc776** [comment] 2023-10-17 06:30
Anyway, I think I know where the problem is:

Can you try commenting out the references to frames 47 and 48 here https://github.com/freedoom/freedoom/blob/master/lumps/dehacked/dehacked.txt#L30C1-L39C13 and see if that addresses the problem?

**Comment by Talon1024** [comment] 2023-10-17 12:16
Yes, that fixes this problem.

> Anyway, I think I know where the problem is:
> 
> Can you try commenting out the references to frames 47 and 48 here https://github.com/freedoom/freedoom/blob/master/lumps/dehacked/dehacked.txt#L30C1-L39C13 and see if that addresses the problem?

**Comment by mc776** [comment] 2023-10-17 15:23
If it happens with this then some other freaky ZScript mod that does something similar with monster hitpoints or something is going to break as well because of the fullbright calls.

I can't imagine how any old mod with any custom Dehacked content wouldn't break similarly as well.

If it were up to me personally I would close this as wontfix as a bug on I.S.'s end, but let's see what others think first.

**Comment by Talon1024** [comment] 2023-10-18 01:23
I think it's best to just leave it for now. I can't think of a solution that would:

- Work only for GZDoom, and
- Play nicely with other mods that modify the DBSG/SSG via DEHACKED

GZDoom doesn't even need the DBSG flash duration fix anyway. I guess GZDoom users can comment out the DEHACKED lines which apply that fix, but AFAIK there's no way to prevent GZDoom from using a DEHACKED patch or specific sections of one.

**Closed** 2023-11-09 01:13 UTC
Labels: bug, question, wontfix, Dehacked
