### ISSUE TITLE
E3M4: can"t get to the round pit sector

### ISSUE THREAD

**Issue by watchmakerful** [freedoom/freedoom#139] opened 2014-12-24 00:49 UTC
There is no way to reach the part with the round pit, all doors leading to it can be opened only from inside.

**Comment by NickZ** [comment] 2015-11-30 21:30
"round pit sector"? The only round pit is in the beginning of the map, and that's open to the player. I can't find any sectors which are supposed to be accessed that are actually inaccessible. Perhaps you misidentified the level?

**Comment by watchmakerful** [comment] 2015-11-30 21:40
I'll try it tomorrow, I don't remember all details. The round pit is at the north end of the map and Player 1 start is on the south edge of the large red pit with a bridge.

**Comment by NickZ** [comment] 2015-12-02 05:01
Aha, I figured it out. The current C3M4 doesn't match your description, but the C3M4 in 0.9 does. It was updated since 0.9, and this issue has been fixed in the current git build.

In the future, if you find a bug, check to see if the issue is also present in the latest git builds. They can be found here: [http://freedoom.soulsphere.org/](http://freedoom.soulsphere.org/) Thanks :smile_cat:

**Closed** 2015-12-02 05:01 UTC
Labels: levels
