### ISSUE TITLE
We should replace hellish things with something of a more creepy, freakish, alien vibe, or make the monsters more demonic

### ISSUE THREAD

**Issue by ElonSatoshi** [freedoom/freedoom#465] opened 2017-07-31 04:05 UTC
I honestly like the former approach; It keeps Freedoom original.

Crucified beings should be replaced with cripplingly mutated beings, fiery graphics should be replaced with something more spooky, mysterious. Make the theme of the 'other world' match that of the monsters. If the monsters aren't hellish, why should anything else be?

**Comment by Voros2** [comment] 2017-07-31 08:22
You have to consider about consistency with other WADs too (or at least as consistent as it can get). Freedoom aims to be compatible with Doom PWADs, so its resources should try to emulate Doom's resources as much as possible without being labeled as a ripoff. Textures are mainly the ones that try to do this, but other stuff like music, don't have to. If someone makes a Hell map for Doom 2, fire and redrocks and all that, how would it look in Freedoom if the fire and redrocks were replaced with mystical purple fire and purple hieroglyphic walls?

Ask yourself this: "What is Hell?" Hell can mean fire and redrocks. Hell can mean a H R Gieger-esque atmosphere. Hell can mean **just another world with an alien civilisation**. Hell could simply be a world similar to Earth. Hell could mean a monochromatic dimension. Hell could mean anything, it's how we choose to interpret Hell, that matters.

For all we know, the monsters do come from this fiery environment which the majority considera as "Hell".

**Comment by Ferk** [comment] 2017-07-31 10:18
To be consistent with other WADs theme I'd personally go the "make the monsters more demonic" route, honestly. Id doesn't have a copyright on horns and tail.
Freedoom's main point always was Doom compatibility while being free-as-in-freedoom. Otherwise why not just play any of the many Doom sci-fi total conversions?

I'm all for Lovecraftian horror type of sci-fi, which means creepy demonic aliens, and it'd make sense to have techy cyborg parts for those monsters that in Doom had tech on them, as well as those with mainly robotic bodies like the arachnotron.

But I don't think it's a good idea to make changes in the general theme of a monster: neither adding tech to monsters that were not supposed to be techy, nor make totally organic anything that might be intended to be robotic (though for the latter I don't think there's such a case). Doing so disrupts the PWADs theme when they use monsters that might be expected to be "sort-of" magical creatures in gothic-themed PWADs. An alien creature can pass for a demon, but a warrior with a high tech armor won't.

I'm thinking on some concepts for a new lost soul I've seen or the current *Hell* Knight and the Baron of *Hell*. It might be true that the concept of "Hell" can follow many different themes, but the problem is that if the theme is different than what the PWAD expects, then it would look out of place and ruin the atmosphere. 

A free-as-in-freedoom total conversion with a sci-fi theme can be done based on Freedoom, and that would be fine. But wouldn't it be good to have also an iwad that is truly compatible with Doom? not only because it supports every Doom sprite, but also because it does it keeping the same theme for use with PWADs.

Imho, Freedoom tries too hard to "not be a rip-off", even though the original goal was actually to be a free-as-in-freedom clone.

**Comment by Voros2** [comment] 2017-07-31 10:32
They seem pretty "demonic" (yet another term that can interpreted as anything) to me :) not to mention that the monster sprites do have a Lovecraftian/Gieger-esque design to them. IIRC, raymoohawk said that he might have taken inspiration/been affected by Lovecraft/Gieger.

**Comment by Ferk** [comment] 2017-07-31 11:48
It's Giger-esque, yes. But unlike Giger's, Lovecraft creatures always felt to me organic and sort of mystical, not really techy. You wouldn't be able to tell if they are really aliens or some creepy creature that has always existed hidden in the depths of the Earth. So they serve better as demon replacement.

Giger creatures would be fine for the ciberdemon, for example. Or if there were demon warriors in doom using armor and tools.
The point is not just about being scary, but that it breaks the atmosphere see technology in monsters that PWADs expect to be more traditional demons.
It's like changing a medieval-looking brick wall texture into a wall of blocks of shiny metal and argue that steel bricks are also bricks.

**Comment by Voros2** [comment] 2017-07-31 12:17
IMO, the current art direction in terms of sprites is alright. What matters most is the consistency, and raymoohawk and cwolf both helped to bring this to the table. People would rather play something with a specific theme rather than a bunch of different things, like fighting T-800 in a Mario-esqe Final Fantasy, or something.

The cyberdemon has tech, but maybe it should have more flesh exposed. It always seemed like it was a machine with face plastered on it. Other than that, the enemy roster seems to grow in a positive way.

**Comment by Ferk** [comment] 2017-07-31 12:29
> What matters most is the consistency

Then you are answering the question on this post already, since this eventually would lead to "replace hellish things with something of a more creepy, freakish, alien vibe" (even more so if for you "hellish" and "alien vibe" can be the same thing).

The problem with this direction is PWAD theme compatibility, like you stated yourself in the first answer.

**Comment by Voros2** [comment] 2017-07-31 13:00
I see what you're getting at :P but that's not what I meant. The OP states replacing crucified beings with crippled mutant beings, and all that, which is basically a transition from Doom Hell to alien world. I'm saying that "Hell" should be fire and brimstone and all that stuff in order to keep compatibilty.

Note: it's quite possible to go down an alien route **without** breaking consistency of Doom PWADs. All we need to prepare for is an additional bloat in filesize, and then renovating/replacing all the maps with "alien" maps where necessary.

**Comment by fragglet** [comment] 2017-08-06 14:10
I'm going to close this bug since it isn't really actionable. While we can certainly expect Freedoom's artwork to evolve over time, that's going to happen when people put in the work to develop new art (like raymoohawk has done). Talking about it in a bug isn't likely to achieve much.

**Closed by fragglet** 2017-08-06 14:10 UTC
