### ISSUE TITLE
FreeDM: map08's music takes a huge pause when looping

### ISSUE THREAD

**Issue by AXDOOMER** [freedoom/freedoom#747] opened 2021-07-25 20:28 UTC
Happens in releases freedm-0.12.1 and latest git build. It even happens in older releases like freedm-0.11, so I don't why I wouldn't have noticed before.  Maybe it's just on my current computer?

Tested with Chocolate-Doom and QZDoom.

**Comment by fawtytoo** [comment] 2022-12-18 12:04
Cannot reproduce with vanilla Doom in DosBox.

**Comment by mc776** [comment] 2023-07-09 20:42
How long is the track supposed to be? I ran around in circles in chocolate for like 4 minutes and didn't hear any pauses.

**Comment by fawtytoo** [comment] 2023-07-10 09:16
This track comes up at 2:50.9 and has no pauses in it.

Cannot reproduce in Chocolate either.

@AXDOOMER Are you sure you don't have a corrupt file, or defective hard drive?

**Comment by AXDOOMER** [comment] 2023-07-11 01:46
> Are you sure you don't have a corrupt file, or defective hard drive?

Lol what does a corrupt hard drive has to do with it? 

The problem must have to do with Timidity or a bug in the OPL emulator. There must be something in this midi track that triggers this bug.

**Comment by mc776** [comment] 2023-07-11 01:50
Are you able to replicate both from a clean install now?

**Comment by AXDOOMER** [comment] 2023-07-11 05:44
The bug still happens with OPL inside Chocolate-doom in freedm-0.12.1, but if you download the latest dev snapshot, the music has been changed. That's why you don't see the issue. If the previous music is still used somewhere, in another map or in FreeDoom 1 or 2, you'll see the bug.

**Comment by mc776** [comment] 2023-07-11 06:01
...yeah that was on me for not checking you were talking about release lol

I looked up the old track and recognized [jute's style](https://github.com/freedoom/freedoom/issues/847) immediately.

Since going forward we're probably going to stick with Korp's DM08 I'll close this.

**Closed by mc776** 2023-07-11 06:01 UTC
Labels: bug, music
