### ISSUE TITLE
Miscellaneous Phase 2 QoL issues

### ISSUE THREAD

**Issue by dftf-stu** [freedoom/freedoom#1230] opened 2023-12-13 12:57 UTC
Greetings!

With things starting to slow-down now for the Christmas period I've time to play some games, and thought I'd do a playthrough of the latest _Freedoom_ "Dev" builds, to see how-far things have come since I last played them.  I usually play them in-order, so thought I'd start with _Phase 2_ this-time!

On _MAP03 "Crude Processing Centre"_ I do find the exit to the map rather abrupt.

In the "Area Map" pickup-room, you go-down the left-hand corridor, call the lift down and the moment you step on it, the map ends!

![DOOM0001](https://github.com/freedoom/freedoom/assets/83965343/ee9cf0db-70ca-437c-a778-bbdde358f5f5) ![DOOM0002](https://github.com/freedoom/freedoom/assets/83965343/44942ca9-8ffa-4939-b639-8e7a4bb07900)

This seems a bit odd, especially given once you collect the "Area Map" and then look on the Automap-screen, you can see a whole area which is inaccessible through normal means -- but which has a proper, modelled exit:

![DOOM0004](https://github.com/freedoom/freedoom/assets/83965343/1c0f7ad3-47c4-4bb0-a6d2-280b6d970822)
![DOOM0005](https://github.com/freedoom/freedoom/assets/83965343/3415b08b-71eb-459a-9b5b-47ae54c98b47) ![DOOM0008](https://github.com/freedoom/freedoom/assets/83965343/0e8198f2-9ff5-4eff-bf88-4b545b183f50)

If you "IDCLIP" to that exit and use it, you still get taken to MAP04, so it doesn't seem like a forgotten secret-exit.  And while I've heard of "multiplayer-only start-areas" (that can sometimes show-up on the Automap), I didn't think "multiplayer-only exists" were a thing?

So... seems a shame not to use that area to me! 🤷🏻‍♂️

(P.S.: apologies if there is any existing-ticket I'm supposed to tack this onto, but I could only find 1181 , which is for Phase 1.  And in the Closed tickets list, I could only-find 101, but that is over nine-years old so doubtful it even applies to the current MAP03!)

**Comment by mc776** [comment] 2023-12-13 18:02
The lift takes you out of the level; the other exit is for the deathmatch containment area.

I wonder if the deathmatch area could just be marked so that it doesn't show on the automap. It's small enough to memorize and nobody has time to check the automap in DM anyway.

I like the lift and the way it implies you're moving to a different place, but it really could be better marked as a map exit.

I wonder if it could be made to match the Map04 start too:
![DOOM00](https://github.com/freedoom/freedoom/assets/24984517/0c382eae-ba65-4800-a341-837ae00cb30f)
![DOOM01](https://github.com/freedoom/freedoom/assets/24984517/9fdebea2-d75d-4378-a30e-bcd3ecb85fa9)

**Comment by unithecutie** [comment] 2023-12-13 18:03
Oh, having it match MAP04's start would be genius.

**Comment by mc776** [comment] 2023-12-13 18:13
[maps.zip](https://github.com/freedoom/freedoom/files/13664177/maps.zip)
![DOOM01](https://github.com/freedoom/freedoom/assets/24984517/e509e04e-4233-4844-b07c-467b14d457a8)
![DOOM00](https://github.com/freedoom/freedoom/assets/24984517/e814a224-3efe-42b0-aeb6-b9e39262a9ac)

**Comment by mc776** [comment] 2023-12-13 18:15
> In MAP09 ("Datacenter"), in the room with the tall-crates, I'd got all three of keycards but could not exit back-out to the previous-area (the corridor with the door to the exit-room), as bars block the exit. ...
> I'd suggest this switch is a bit-easy to miss...

I thought (somehow, as the person who designed this) I was the only one who kept missing that. Will take a look later.

**Comment by dftf-stu** [comment] 2023-12-13 22:02
@mc776 having the lift match looks better, yes.  Before I'd not even thought that in MAP04 I was now above where I was in MAP03!  Thanks for explaining why the "inaccessible area" exists, too -- though still a pity I can't access it in single-player!  (I seem to recall C2M1 had a [similar issue](https://github.com/freedoom/freedoom/issues/864) where there was an area over-the-gap near where you start, though I notice in the recent "Dev" builds that map has been entirely-replaced now, anyway.)

Maybe as a quick-fix for MAP03 the "Area Map" pickup could be removed, so the deathmatch-only area cannot be seen?

**Comment by dftf-stu** [comment] 2023-12-13 22:30
Some feedback for the _Phase 2_ maps I have played so-far:
- **MAP01:** in the blue, central-courtyard area there is zombie who constantly looks at a metal-door and doesn't awaken unless you shoot within that area.  While I know he has been placed there to hint about a secret, it does come-over a bit odd
- **MAP02:** odd there is only one secret on this map... and I'd imagine most-people will easily find it. 🤷🏻‍♂️
- **MAP03:** only the issues I've already mentioned
- **MAP04:** one of the secrets in the level expects you to be rather-quick to access it!
- **MAP05:** in the "ambush-room", where you get the yellow keycard, some of the Minigunners don't awaken and you'll only find them if you look behind the rocks.  Might disrupt those going for 100% kills
- **MAP06:** similar to MAP02, another really-easy secret: the Minigun in the "garden area"
- **MAP07:** I find the number of small-rooms all close-together near the starting-area makes it a bit tricky to navigate and remember which path then takes you to which larger area
- **MAP08:** after I took the teleport for the first time, I found the door to the left locked, and so went right and through the door there, down to the basement, only to find bars blocking my way.  Once you teleport I'd say it's not totally-obvious you have to drop-down, then go back-up to the starting-area and then through a door which has opened to obtain the yellow keycard.  I'd move the yellow keycard to the room the teleport takes you to, and keep the exit-area locked until near the end
- **MAP09:** in the nukage-room, where you obtain the red keycard, there is a 'rad-suit' which feels somewhat needless, as there are no secrets to be found by venturing down into the ooze.  Also, as a minor issue, in that same room a box of missiles near the switch partially overhangs the edge
- **MAP10:** the organic, outdoor and cave areas of this map are fun, though the indoor areas near the end aren't as interesting, and in the final "fireblu" room, an "EXIT" sign may help as it may not be obvious to all players you're supposed to drop-down into the lava and run into the hole

**Comment by unithecutie** [comment] 2023-12-13 22:38
* MAP01: Easily rotated.
* MAP02: I think the SSG secret is tagged as such to prevent having no secrets? Which makes the stats screen say 0% in vanilla.
* MAP05: Move the chaingunners to the teleporting star thing?
* MAP06: The secret tag for this can just be removed, it doesn't have the same sort of bug as MAP02.
* MAP07: I agree that this map is hard to navigate; but hey, at least it isn't the old "Dead Simple" clone.
* MAP08: This map is slightly confusing, but I don't think it needs too much of a change.

**Comment by mc776** [comment] 2023-12-13 22:42
*Map08* is confusing. I recall someone was working on a major overhaul of it that makes it much easier to navigate but I dont' know where we are with that.

**Comment by mc776** [comment] 2023-12-13 22:54
I think it's best to just leave the Map01 zombie as-is. It's too easy to get into LOS with it long before you're conscious of that area.

Map02 could just flat-out use a secret.

Map05 minigunner is a hilarious mean prank - someone makes a desperate dash for that stimpack and lol. Once  a player sees it they will not forget it on their next attempt.

Map06 is *not* obvious to someone who isn't used to how the third dimension works in Doom. It's appropriate for an earlier level. (Personally I'd have made sector 64 (the one where you have to walk backwards off the teleport) a secret too...)

Map09 radsuit's good to have if you know you're kinda clumsy when dodging lots of monsters at once.

I think Map10's fine. Like I do get the bit of pause it gives but I think the player can figure it out well enough (unlike the Map03 lift or the former Map23 broken teleporter)

**Comment by mc776** [comment] 2023-12-15 02:06
I've taken the liberty to edit the title to match the rest of the discussion in the comments, in lieu of closing this issue as done.

**Comment by dftf-stu** [comment] 2023-12-15 17:49
**MAP11:** I thought I'd give its own comment as I've a fair-bit to say!

**Starting area:**
- it would be great if each of the three doors indicate which colour key they lead to (oddly, this is something which the older 0.12.1 version of this map did do, by having coloured-bars near the ceiling of each door)
- it's nice though how in this version of the map you can go for the keys in any-order

**Blue Key route:**
- the door into the stone (castle?) says "blue key needed for this door", and I guess the intended-way to get in is to use the lift to the left.  However, the monsters inside the castle can open the door from their-side -- not sure if that's intended?
- the "castle" room, and the room where you go down in the lift and have enemies shooting at you from an area behind a mesh-fence, both feel a little-similar to rooms from MAP11 of DOOM II?  (Though less-similar than they were in 0.12.1!)

**Yellow Key route:**
- the first metal-door (near the mesh-fence secret-room) says "yellow key needed", but you actually open this door via a switch in the monster-closet of the previous room; once open, it stays permanently-open.  (Whereas in 0.12.1, the door is timed and you have to run through it.)  So... not-sure why the message about needing the key?
- The arena-area, where you get the yellow key is a bit confusing.  Firstly, in the green-corridor area you press a switch and it's not-obvious what it does -- it lowers a segment of wall, which is a lift that takes you down to the arena.  In 0.12.1, this was just a standard-door and much-easier to notice what had happened!  Once in the arena itself, there is a bit too-much back-and-forth, I think: go to the far-side; press the switch on the podium; go-back to the previous, green area; press the second switch, now the bars blocking it have gone; go back into the arena; get the yellow-key, now the podium has lowered; then press the switch that was behind the podium to open the exit-door -- which is timed, so run!  Oh, and compared to 0.12.1, where the exit-door opening was easier-to-see from the podium, I honestly didn't know how to get-out in the new map as you can barely see the lift come-down from where the switch is, given how dark the room is!  Honestly, if it were me I'd get-rid of the second-switch in the green-area entirely, and just add a switch into each of the alcoves within the arena itself and keep everything self-contained.

**Red Key route:**
- In the "E1M1 tribute area", I initially missed the switch on the left-hand column and got stuck in that area until I found it.  Similar to my issue with MAP09 earlier, switches that are essential to complete a level should be more-obvious to find.  Maybe the switch instead could be put at the top of the stairs (where the Minigunners are) and that "cube" could lower as you go up to reveal an enemy, with the switch behind them?

**General points:**
- This map overall took me about 45-50 minutes to finish, and feels somewhat overly-long: I went back to the 0.12.1 release after and played that version and it took me just 25-30 minutes -- and I found all of the secrets in that one, too...
- ...whereas in this newer version, I couldn't find all of them, and only found three of the "Commander Keen" replacement things, but not the fourth.  I feel in the newer version, things are a little too-cryptic now.

**Comment by mc776** [comment] 2023-12-15 22:52
I am strongly in favour of getting rid of all key-colour-trimmed doors to mark routes leading *to* a key of that colour, instead of the usual, well-established (and actually described in the manual) visual language of that trim marking doors that are locked and *need* that key. It's really unnecessarily confusing and the only place where it really works is Map32 because Map32 is intentionally cruel to the player.

All the big doors are carefully tested and work exactly as intended.

**Comment by mc776** [comment] 2023-12-15 22:53
At this point this is becoming a long meandering thread about one' opinions on some maps, without anything immediately actionable. With respect, I think it's best we close it.

**Closed by mc776** 2023-12-15 22:53 UTC
Labels: enhancement, levels

**Comment by dftf-stu** [comment] 2023-12-15 23:42
@mc776 oh, that's a bit disappointing... I'd just finished MAP20 and had some feedback for those batch of levels. 🙁

Assuming that you actually do want feedback from players(?) then how is best to go about it? 🤔

**Comment by dftf-stu** [comment] 2023-12-15 23:56
I'll at-least mention these floating clips on MAP14 (route to the blue-key, I think it was) as clearly this an actual error:

![DOOM0039](https://github.com/freedoom/freedoom/assets/83965343/a02b5f8d-9fc6-4e87-8289-3a18bf1efdd7)

Guessing there used to be some steps there in an older revision of the map? 🤔

**Comment by mc776** [comment] 2023-12-16 02:04
That's a side effect of the item's collision box being much larger than the sprite. This happens in id as well. The only way to fix the visual anomaly is to make every sprite at least 32 pixels wide which would make no sense for the clip pickup.

These are drops by the dying zombies rather than placed on the map by the mapper, so there's nothing we can really do about them.

**Comment by dftf-stu** [comment] 2023-12-16 09:23
@mc776 I guess the issue might be that the Zombies those clips come-from start-out floating? 👻

![DOOM0002](https://github.com/freedoom/freedoom/assets/83965343/9c8a31a8-127c-4970-8a13-00f1f7e21f10)

I guess I must have killed them both quickly, and so only noticed the clips floating, after their corpses fell to the floor.

Oddly though, when I did an IDCLIP to try and get a cleaner-screenshot, they then don't float:

![DOOM0004](https://github.com/freedoom/freedoom/assets/83965343/b61347d6-2bc4-4a3d-8d2d-50dd2fd295a5)

So... is this an issue with my "source port" perhaps?
I'm using _Crispy DOOM_, though I thought _Freedoom_ targeted vanilla, so... it should work? 🤷🏻‍♂️

**Comment by mc776** [comment] 2023-12-16 20:56
Known vanilla behaviour. Very common and most of the time you just don't notice because you're going too fast.
