### ISSUE TITLE
textures: STARBR1 disappears when you load Double Impact.

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom#1005] opened 2023-07-04 02:39 UTC
To replicate:
1. load dbimpact.wad in Freedoom in Eternity or dsda-doom.
2. warp to E4M1.

Expected: Freedoom's version of DI loads normally.
Actual: step outside and see a bunch of HOM/missing texture errors in the front of the building around the door.

DI's TEXTURES entries do not appear to overwrite STARBR1 at all (nor patches SW11_4 or SW11_5) so it's not clear what is happening.

DI itself seems to be fine, though, and for some reason this bug does *not* appear in Chocolate, so this is more of an annoyance than anything super high priority.

**Comment by Xindage** [comment] 2023-07-04 10:37
it does hapeen in chocolate but in a way worse way: R_TextureNumForName: STARBR1 not found.
I explained it but seems like you missed the part where its the error, i'll post you again:

"The Doom engine looks up a texture name using the wall texture lumps TEXTURE1 and TEXTURE2. (TEXTURE1 is present in all Doom versions; TEXTURE2 supports the additional textures in registered/Ultimate Doom, but is not found in Doom II.) This yields a list of indices into the PNAMES lump. For each index, PNAMES gives the name of a lump known as a wall patch; each wall patch lump is stored in Doom's picture format. Rendering the texture's list of patches gives the final texture graphic that can be applied to any wall surface.

As with most lumps, if you replace a TEXTUREx lump in a PWAD, the original IWAD lump will not be loaded. Therefore you need to copy the existing texture definitions from the IWAD into your PWAD, alongside any new ones. For Doom II, you can take advantage of the missing TEXTURE2 lump and provide just new or changed texture definitions in that lump."

Source: https://doomwiki.org/wiki/Texture

Closed as not a bug.

**Closed by Xindage** 2023-07-04 10:37 UTC

**Comment by mc776** [comment] 2023-07-04 15:08
It seems like I'd left a second "-file" call when I was trying this in Chocolate, hence why I hadn't run into this error.
