### ISSUE TITLE
Choose port for player, naming and versioning convenience

### ISSUE THREAD

**Issue by XCOPY-** [freedoom/freedoom#164] opened 2015-09-10 15:32 UTC
We should adopt a source-port for our, and players convenience. The source-port developers does not always sync our release cycle with theirs, and their position is understandable. I realized that a few questions needs to be answered:

* Will the maps keep being Boom compatible?
* What is our focus? Multiplayer? Single-player? (keep in mind people will wonder if multiplayer is possible anyway)

Then we can proceed to decide which port to adopt. I made one package myself (no folder hierarchy due to some limitations I found in the process), which includes the ports that I think are better suited for online play. The launcher used shows its limits when the player wants to make a server, sadly.

https://mega.co.nz/#!UABQALSB!iWwlRzz-u6a7_Bnaum5LDuSPV0rlA8sAtJdUwpMTDs8

I tried to configure the ports to feel as seamless as possible, here are the configuration files:

https://mega.co.nz/#!wRRA0a7I!leoVKckBbWGHxK-5H7MEMpfXE58eZY_pebUXskwDT2Q

There is a discussion going on at http://www.doomworld.com/vb/freedoom/74538-we-need-convenience/

**Comment by chungy** [comment] 2015-09-10 15:52
This kind of flows into #110, although I regret I haven't done much about it since I posted the original issue.

Presently we are heavily recommending Odamex as it's rather simple for single and multi-player, as well as fitting into Freedoom's free software philosophy (not to dis Zandronum or ZDaemon -- but they don't fit into that philosophy). Sticking to just one port massively helps reduce confusion, and I have had a somewhat disturbing amount of emails and contacts about how to play the game at all, the separation between data and engine, and why $NON_BOOM_COMPAT_PORT won't run the game (and some not unjustified complaints about how it shouldn't be so restricted).

Thanks for the effort, it's heavily appreciated, and being able to run the game simply is something that should always be thought about.

**Comment by fragglet** [comment] 2015-09-10 17:28
I think this should just be closed as as a dupe of #110.

There's great value in distributing an installable bundle of Freedoom packaged with a source port, but I don't see any point in distributing more than one source port. We should just pick one, and Odamex seems like a good choice. Including more than one source port will just make things needlessly convoluted, and the goal here should be simplicity.

**Closed** 2015-09-10 21:12 UTC
