### ISSUE TITLE
Should freedoom have an option to download a file with freedoom with GZDoom?

### ISSUE THREAD

**Issue by CraftedPixel** [freedoom/freedoom#249] opened 2016-03-15 00:17 UTC
We can instead of having the user go out and get an engine to play freedoom why not have a .zip file with all they need to play freedoom?

**Comment by fragglet** [comment] 2016-03-15 00:29
Duplicate of #110 I believe.

Note that GZDoom isn't an option because it is not free software.

**Closed by fragglet** 2016-03-15 00:29 UTC
